## need to add server.  entries to enable HTTPS with SSL keystore, replace "????" with correct entries

server.port=8443
security.require-ssl=true
server.ssl.key-alias=Talia
server.ssl.key-store-password=Argentia
server.ssl.key-store=classpath:keystore.jks
server.ssl.key-store-type=JKS

